language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# TODO why was pandas (seeming to) fail to install on their server with this
# version? fix?
#  - "pypy3.5"
install:
  - pip install .
  - pip install -r test_requirements.txt
script: pytest
